### ISSUE TITLE
Tests no longer included in tarball

### ISSUE THREAD

**Issue by aviau** [borntyping/python-riemann-client#22]
Hello,

Is there a reason tests are no longer included in the pypi tarball?

Thanks!

**Comment by borntyping** [comment]
They were moved as part of https://github.com/borntyping/python-riemann-client/pull/20, but I don't know if there was any reason for it. /cc @nisanharamati

**Comment by nisanharamati** [comment]
When tests was inside, you could run into import errors by doing `from riemann_client import *`, where it would import the `tests` submodule and run into dependencies that weren't installed by `setup.py`, because they're only listed in `tox.ini`. 
Also, the tests have an additional set of dependencies that aren't required for running the client itself. When running on lean servers it's common to separate the dev (and test) requirements list from the production one in order to minimize the dependency tree.

I did miss https://github.com/borntyping/python-riemann-client/blob/master/tox.ini#L29 which can be omitted now, though.

**Comment by aviau** [comment]
In Debian, we run tests twhen they are included in the tarball. This helps us determine if libraries we are shipping are compatible or not.

Adding it to MANIFEST will include the tests in the tarball and keep them out of the riemann_client package.

Can you merge #23 please?

**Comment by aviau** [comment]
//cc @borntyping

**Comment by borntyping** [comment]
I'll tag and push this in the morning (GMT) :smile:

**Comment by aviau** [comment]
Thanks!
